server:
  port: 80

spring:
  application:
    name: order-hystrix-server

eureka:
  client:
    register-with-eureka: false       # 不注册到 Eureka Server，只从那儿拿到支付服务的地址
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

feign:
  hystrix:
    enabled: true


logging:
  level:
    org.example.cloud.order.controller.OrderController: debug
    org.example.cloud.order.service.PaymentService: debug

