server:
  port: 8001

spring:
  application:
    name: payment-hystrix-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka         # Eureka Server 这里只使用单机模式