server:
  port: 7002

eureka:
  instance:
    hostname: eureka-server-2
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://eureka-server-1:7001/eureka        # 集群模式
      defaultZone: http://eureka-server-2:7002/eureka         # standalone mode